import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { pool, admin } from '../db/index';
import * as response from '../utils/response';
import { AuthRequest } from '../middleware/auth';
import { logAction } from '../services/auditService';
import { sendWelcomeEmail } from '../services/emailService';

export const createUser = async (req: AuthRequest, res: Response) => {
  const { email, password, name, role, details, autoGeneratePassword } = req.body;

  const isAutoGenerated = !!autoGeneratePassword || !password;
  const plainTextPassword = isAutoGenerated
    ? crypto.randomBytes(8).toString('hex')
    : password;

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const existing = await client.query(
      'SELECT id FROM users WHERE email = $1',
      [email]
    );
    if (existing.rows.length > 0) {
      await client.query('ROLLBACK');
      return response.error(res, 'A user with that email already exists.', 'CONFLICT', 409);
    }

    const hashedPass = await bcrypt.hash(plainTextPassword, 12);

    const result = await client.query(
      `INSERT INTO users (email, password, name, role, status)
       VALUES ($1, $2, $3, $4, 'verified')
       RETURNING id, email, name, role, status`,
      [email, hashedPass, name, role]
    );
    const user = result.rows[0];

    if (role === 'tanod') {
      await client.query(
        `INSERT INTO patrols (tanod_id, tanod_name, is_active, status)
         VALUES ($1, $2, false, 'offline')`,
        [user.id, name]
      );
    }

    if (role === 'resident') {
      await client.query(
        `INSERT INTO residents
           (id, name, status, phone, address, house_number, household_size,
            blood_type, medical_conditions,
            emergency_contact_name, emergency_contact_phone)
         VALUES ($1, $2, 'approved', $3, $4, $5, $6, $7, $8, $9, $10)
         ON CONFLICT (id) DO NOTHING`,
        [
          user.id, name,
          details?.phone || null, details?.address || null, details?.houseNumber || null,
          details?.householdSize !== undefined ? Number(details.householdSize) : 1,
          details?.bloodType || null, details?.medicalConditions || null,
          details?.emergencyContactName || null, details?.emergencyContactPhone || null
        ]
      );
    }

    // Firebase Auth Sync
    let firebaseUid: string | null = null;
    if (admin && admin.apps && admin.apps.length > 0) {
      try {
        const fbUser = await admin.auth().createUser({
          email: email.toLowerCase(),
          password: plainTextPassword,
          displayName: name,
        });
        firebaseUid = fbUser.uid;
        console.log(`[Admin] Programmatic Firebase User created: ${fbUser.uid}`);
      } catch (fbErr: any) {
        if (fbErr.code === 'auth/email-already-exists') {
          try {
            const fbUser = await admin.auth().getUserByEmail(email.toLowerCase());
            firebaseUid = fbUser.uid;
            console.log(`[Admin] Firebase User already exists: ${fbUser.uid}`);
          } catch (fbGetErr: any) {
            console.error(`[Admin] Failed to retrieve existing Firebase User:`, fbGetErr.message);
          }
        } else {
          console.error(`[Admin] Failed programmatic Firebase User creation:`, fbErr.message);
        }
      }

      if (firebaseUid) {
        try {
          await admin.auth().setCustomUserClaims(firebaseUid, { role });
          console.log(`[Admin] Firebase Custom Claims synced for ${email} with role: ${role}`);
        } catch (claimsErr: any) {
          console.error(`[Admin] Failed to set Firebase Custom Claims:`, claimsErr.message);
        }
      }
    }

    await logAction(req.user!.id, 'ADMIN_CREATE_USER', 'users', user.id, {
      createdRole: role,
      createdEmail: email,
    });

    await client.query('COMMIT');

    // Safe, asynchronous, resilient welcome communication trigger
    try {
      await sendWelcomeEmail({
        email: email.toLowerCase(),
        name,
        role,
        temporaryPassword: plainTextPassword,
        isAutoGenerated,
      });
    } catch (emailErr: any) {
      console.error('[Admin] Welcome email trigger failed:', emailErr.message);
    }

    return response.success(res, { user }, 'User created successfully.', 201);
  } catch (err: any) {
    await client.query('ROLLBACK');
    console.error('[Admin] createUser error:', err.message);
    return response.error(res, 'Failed to create user. Please try again.');
  } finally {
    client.release();
  }
};

export const listUsers = async (req: AuthRequest, res: Response) => {
  try {
    const result = await pool.query(
      `SELECT id, email, name, role, status, created_at, last_active
       FROM users
       ORDER BY created_at DESC`
    );
    return response.success(res, result.rows);
  } catch (err: any) {
    console.error('[Admin] listUsers error:', err.message);
    return response.error(res, 'Failed to fetch users.');
  }
};

export const updateUserRole = async (req: AuthRequest, res: Response) => {
  const { id } = req.params;
  const { role } = req.body;

  const allowedRoles = ['resident', 'tanod', 'admin', 'superadmin'];
  if (!allowedRoles.includes(role)) {
    return response.error(res, 'Invalid role specified.', 'BAD_REQUEST', 400);
  }

  try {
    const result = await pool.query(
      `UPDATE users SET role = $1 WHERE id = $2
       RETURNING id, email, name, role, status`,
      [role, id]
    );
    if (result.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    const userObj = result.rows[0];

    // Sync custom claims to Firebase
    if (userObj && admin && admin.apps && admin.apps.length > 0) {
      try {
        const fbUser = await admin.auth().getUserByEmail(userObj.email.toLowerCase());
        await admin.auth().setCustomUserClaims(fbUser.uid, { role });
        console.log(`[Admin] Custom claims updated on role change for firebase user ${fbUser.uid} to: ${role}`);
      } catch (fbErr: any) {
        console.warn(`[Admin] Could not update custom claims on role change for ${userObj.email}:`, fbErr.message);
      }
    }

    await logAction(req.user!.id, 'ADMIN_UPDATE_ROLE', 'users', id, {
      newRole: role,
    });

    return response.success(res, userObj, 'User role updated.');
  } catch (err: any) {
    console.error('[Admin] updateUserRole error:', err.message);
    return response.error(res, 'Failed to update role.');
  }
};

export const updateUserStatus = async (req: AuthRequest, res: Response) => {
  const { id } = req.params;
  const { status } = req.body;

  const allowedStatuses = ['pending', 'verified', 'suspended'];
  if (!allowedStatuses.includes(status)) {
    return response.error(res, 'Invalid status specified.', 'BAD_REQUEST', 400);
  }

  try {
    const result = await pool.query(
      `UPDATE users SET status = $1 WHERE id = $2
       RETURNING id, email, name, role, status`,
      [status, id]
    );
    if (result.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    await logAction(req.user!.id, 'ADMIN_UPDATE_STATUS', 'users', id, {
      newStatus: status,
    });

    return response.success(res, result.rows[0], 'User status updated.');
  } catch (err: any) {
    console.error('[Admin] updateUserStatus error:', err.message);
    return response.error(res, 'Failed to update status.');
  }
};

export const deleteUser = async (req: AuthRequest, res: Response) => {
  const { id } = req.params;

  // Prevent self-deletion
  if (req.user!.id === id) {
    return response.error(res, 'You cannot delete your own account.', 'FORBIDDEN', 403);
  }

  try {
    const result = await pool.query(
      'DELETE FROM users WHERE id = $1 RETURNING id, email, role',
      [id]
    );
    if (result.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    await logAction(req.user!.id, 'ADMIN_DELETE_USER', 'users', id, {
      deletedEmail: result.rows[0].email,
      deletedRole: result.rows[0].role,
    });

    return response.success(res, null, 'User deleted successfully.');
  } catch (err: any) {
    console.error('[Admin] deleteUser error:', err.message);
    return response.error(res, 'Failed to delete user.');
  }
};
