import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { pool, admin } from '../db/index';
import { syncUserRoleToFirebase } from './authController';
import * as response from '../utils/response';
import { AuthRequest } from '../middleware/auth';
import { encrypt } from '../utils/crypto';
import { logAdminAction } from '../services/auditService';
import { sendWelcomeEmail } from '../services/emailService';

export const createUser = async (req: AuthRequest, res: Response) => {
  const { email, password, name, role, details, autoGeneratePassword } = req.body;

  const isAutoGenerated = !!autoGeneratePassword || !password;
  const plainTextPassword = isAutoGenerated
    ? crypto.randomBytes(8).toString('hex')
    : password;

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const existing = await client.query(
      'SELECT id FROM users WHERE email = $1',
      [email]
    );
    if (existing.rows.length > 0) {
      await client.query('ROLLBACK');
      return response.error(res, 'A user with that email already exists.', 'CONFLICT', 409);
    }

    const hashedPass = await bcrypt.hash(plainTextPassword, 12);

    const result = await client.query(
      `INSERT INTO users (email, password, name, role, status)
       VALUES ($1, $2, $3, $4, 'verified')
       RETURNING id, email, name, role, status`,
      [email, hashedPass, name, role]
    );
    const user = result.rows[0];

    if (role === 'tanod') {
      await client.query(
        `INSERT INTO patrols (tanod_id, tanod_name, is_active, status)
         VALUES ($1, $2, false, 'offline')`,
        [user.id, name]
      );
    }

    if (role === 'resident') {
      const bloodTypeEnc = details?.bloodType ? encrypt(details.bloodType) : null;
      const medicalConditionsEnc = details?.medicalConditions ? encrypt(JSON.stringify(details.medicalConditions)) : null;

      await client.query(
        `INSERT INTO residents
           (id, name, status, phone, address, house_number, household_size,
            blood_type_enc, medical_conditions_enc,
            emergency_contact_name, emergency_contact_phone)
         VALUES ($1, $2, 'approved', $3, $4, $5, $6, $7, $8, $9, $10)
         ON CONFLICT (id) DO NOTHING`,
        [
          user.id, name,
          details?.phone || null, details?.address || null, details?.houseNumber || null,
          details?.householdSize !== undefined ? Number(details.householdSize) : 1,
          bloodTypeEnc, medicalConditionsEnc,
          details?.emergencyContactName || null, details?.emergencyContactPhone || null
        ]
      );
    }

    // Firebase Auth Sync
    let firebaseUid: string | null = null;
    if (admin && admin.apps && admin.apps.length > 0) {
      try {
        const fbUser = await admin.auth().createUser({
          email: email.toLowerCase(),
          password: plainTextPassword,
          displayName: name,
        });
        firebaseUid = fbUser.uid;
        console.log(`[Admin] Programmatic Firebase User created: ${fbUser.uid}`);
      } catch (fbErr: any) {
        if (fbErr.code === 'auth/email-already-exists') {
          try {
            const fbUser = await admin.auth().getUserByEmail(email.toLowerCase());
            firebaseUid = fbUser.uid;
            console.log(`[Admin] Firebase User already exists: ${fbUser.uid}`);
          } catch (fbGetErr: any) {
            console.error(`[Admin] Failed to retrieve existing Firebase User:`, fbGetErr.message);
          }
        } else {
          console.error(`[Admin] Failed programmatic Firebase User creation:`, fbErr.message);
        }
      }

      if (firebaseUid) {
        try {
          await admin.auth().setCustomUserClaims(firebaseUid, { role });
          console.log(`[Admin] Firebase Custom Claims synced for ${email} with role: ${role}`);
        } catch (claimsErr: any) {
          console.error(`[Admin] Failed to set Firebase Custom Claims:`, claimsErr.message);
        }
      }
    }

    await logAdminAction({
      adminId: req.user!.id,
      action: 'ADMIN_CREATE_USER',
      targetTable: 'users',
      targetId: user.id,
      details: {
        createdRole: role,
        createdEmail: email,
      }
    });

    await client.query('COMMIT');

    // Safe, asynchronous, resilient welcome communication trigger
    try {
      await sendWelcomeEmail({
        email: email.toLowerCase(),
        name,
        role,
        temporaryPassword: plainTextPassword,
        isAutoGenerated,
      });
    } catch (emailErr: any) {
      console.error('[Admin] Welcome email trigger failed:', emailErr.message);
    }

    return response.success(res, { user }, 'User created successfully.', 201);
  } catch (err: any) {
    await client.query('ROLLBACK');
    console.error('[Admin] createUser error:', err.message);
    return response.error(res, 'Failed to create user. Please try again.');
  } finally {
    client.release();
  }
};

export const listUsers = async (req: AuthRequest, res: Response) => {
  try {
    const result = await pool.query(
      `SELECT id, email, name, role, status, created_at, last_active
       FROM users
       ORDER BY created_at DESC`
    );
    return response.success(res, result.rows);
  } catch (err: any) {
    console.error('[Admin] listUsers error:', err.message);
    return response.error(res, 'Failed to fetch users.');
  }
};

export const updateUserRole = async (req: AuthRequest, res: Response) => {
  const { id } = req.params;
  const { role } = req.body;

  const allowedRoles = ['resident', 'tanod', 'admin', 'superadmin'];
  if (!allowedRoles.includes(role)) {
    return response.error(res, 'Invalid role specified.', 'BAD_REQUEST', 400);
  }

  try {
    const result = await pool.query(
      `UPDATE users SET role = $1 WHERE id = $2
       RETURNING id, email, name, role, status`,
      [role, id]
    );
    if (result.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    const userObj = result.rows[0];

    // Sync custom claims to Firebase using the high-performance fast path
    await syncUserRoleToFirebase(id, role);

    await logAdminAction({
      adminId: req.user!.id,
      action: 'ADMIN_UPDATE_ROLE',
      targetTable: 'users',
      targetId: id,
      details: {
        newRole: role,
      }
    });

    return response.success(res, userObj, 'User role updated.');
  } catch (err: any) {
    console.error('[Admin] updateUserRole error:', err.message);
    return response.error(res, 'Failed to update role.');
  }
};

export const updateUserStatus = async (req: AuthRequest, res: Response) => {
  const { id } = req.params;
  const { status } = req.body;

  const allowedStatuses = ['pending', 'verified', 'suspended'];
  if (!allowedStatuses.includes(status)) {
    return response.error(res, 'Invalid status specified.', 'BAD_REQUEST', 400);
  }

  try {
    const result = await pool.query(
      `UPDATE users SET status = $1 WHERE id = $2
       RETURNING id, email, name, role, status`,
      [status, id]
    );
    if (result.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    await logAdminAction({
      adminId: req.user!.id,
      action: 'ADMIN_UPDATE_STATUS',
      targetTable: 'users',
      targetId: id,
      details: {
        newStatus: status,
      }
    });

    return response.success(res, result.rows[0], 'User status updated.');
  } catch (err: any) {
    console.error('[Admin] updateUserStatus error:', err.message);
    return response.error(res, 'Failed to update status.');
  }
};

export const deleteUser = async (req: AuthRequest, res: Response) => {
  const { id } = req.params;

  // Prevent self-deletion
  if (req.user!.id === id) {
    return response.error(res, 'You cannot delete your own account.', 'FORBIDDEN', 403);
  }

  try {
    const result = await pool.query(
      'DELETE FROM users WHERE id = $1 RETURNING id, email, role',
      [id]
    );
    if (result.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    await logAdminAction({
      adminId: req.user!.id,
      action: 'ADMIN_DELETE_USER',
      targetTable: 'users',
      targetId: id,
      details: {
        deletedEmail: result.rows[0].email,
        deletedRole: result.rows[0].role,
      }
    });

    return response.success(res, null, 'User deleted successfully.');
  } catch (err: any) {
    console.error('[Admin] deleteUser error:', err.message);
    return response.error(res, 'Failed to delete user.');
  }
};

export const resendWelcomeEmail = async (req: AuthRequest, res: Response) => {
  const { userId } = req.body;

  if (!userId) {
    return response.error(res, 'User ID is required.', 'BAD_REQUEST', 400);
  }

  try {
    const userResult = await pool.query(
      `SELECT id, email, name, role FROM users WHERE id = $1`,
      [userId]
    );

    if (userResult.rows.length === 0) {
      return response.error(res, 'User not found.', 'NOT_FOUND', 404);
    }

    const user = userResult.rows[0];

    // Generate a new temporary passcode
    const newTempPassword = crypto.randomBytes(8).toString('hex');
    const hashedPassword = await bcrypt.hash(newTempPassword, 12);

    // Update password in PostgreSQL DB
    await pool.query(
      `UPDATE users SET password = $1 WHERE id = $2`,
      [hashedPassword, user.id]
    );

    // Sync state to Firebase Auth password
    if (admin && admin.apps && admin.apps.length > 0) {
      try {
        const fbUser = await admin.auth().getUserByEmail(user.email.toLowerCase());
        await admin.auth().updateUser(fbUser.uid, { password: newTempPassword });
        console.log(`[Admin] Reset password in Firebase Auth successfully for: ${user.email}`);
      } catch (fbErr: any) {
        console.error(`[Admin] Failed to update password in Firebase Auth: ${fbErr.message}`);
      }
    }

    // Call auditor log for compliance
    await logAdminAction({
      adminId: req.user!.id,
      action: 'ADMIN_RESEND_WELCOME',
      targetTable: 'users',
      targetId: user.id,
      details: {
        targetEmail: user.email,
        targetRole: user.role,
      }
    });

    // Trigger the physical or console email notification safely
    try {
      await sendWelcomeEmail({
        email: user.email.toLowerCase(),
        name: user.name,
        role: user.role,
        temporaryPassword: newTempPassword,
        isAutoGenerated: true,
      });
    } catch (emailErr: any) {
      console.error('[Admin] Resend welcome communication failed:', emailErr.message);
    }

    return response.success(res, null, 'Welcome email with new passcode sent successfully.');
  } catch (err: any) {
    console.error('[Admin] resendWelcomeEmail error:', err.message);
    return response.error(res, 'Failed to resend welcome email.');
  }
};

export const getAuditLogs = async (req: AuthRequest, res: Response) => {
  try {
    const result = await pool.query(
      `SELECT id, admin_id, action, target_table, target_id, details, created_at
       FROM audit_logs
       ORDER BY created_at DESC
       LIMIT 100`
    );
    return response.success(res, result.rows);
  } catch (err: any) {
    console.error('[Admin] getAuditLogs error:', err.message);
    return response.error(res, 'Failed to fetch audit logs.');
  }
};

export const approveResident = async (req: AuthRequest, res: Response) => {
  const { residentId, registerInFirebase, sendEmail } = req.body;
  if (!residentId) {
    return response.error(res, 'residentId is required', 'BAD_REQUEST', 400);
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // 1. Get resident details
    const resResult = await pool.query(
      `SELECT r.*, u.email, u.name, u.firebase_uid FROM residents r 
       JOIN users u ON r.id = u.id 
       WHERE r.id = $1`,
      [residentId]
    );

    if (resResult.rowCount === 0) {
      await client.query('ROLLBACK');
      return response.error(res, 'Resident not found', 'NOT_FOUND', 404);
    }

    const resident = resResult.rows[0];

    // Create Firebase account if requested and NOT already created
    let firebaseUid = resident.firebase_uid;
    let tempPassword = crypto.randomBytes(8).toString('hex');

    if (registerInFirebase && admin && admin.apps && admin.apps.length > 0) {
      try {
        const fbUser = await admin.auth().createUser({
          email: resident.email,
          password: tempPassword,
          displayName: resident.name,
        });
        firebaseUid = fbUser.uid;

        // Save firebase_uid to PostgreSQL
        await client.query(
          `UPDATE users SET firebase_uid = $1 WHERE id = $2`,
          [firebaseUid, resident.id]
        );
      } catch (fbErr: any) {
        if (fbErr.code === 'auth/email-already-exists') {
          // Get existing instead
          try {
            const existingFb = await admin.auth().getUserByEmail(resident.email);
            firebaseUid = existingFb.uid;
            await client.query(
              `UPDATE users SET firebase_uid = $1 WHERE id = $2`,
              [firebaseUid, resident.id]
            );
          } catch (getFbErr) {
            console.error('[Admin] Failed to lookup Firebase user:', getFbErr);
          }
        } else {
          throw fbErr;
        }
      }
    }

    // Update status in PostgreSQL for both tables
    await client.query(`UPDATE users SET status = 'verified' WHERE id = $1`, [residentId]);
    await client.query(
      `UPDATE residents SET status = 'approved', is_verified = true, verification_date = now() WHERE id = $1`,
      [residentId]
    );

    await client.query('COMMIT');

    // Sync roles to Firebase custom claims
    if (firebaseUid && admin && admin.apps && admin.apps.length > 0) {
      try {
        await admin.auth().setCustomUserClaims(firebaseUid, { role: 'resident' });
      } catch (syncErr: any) {
        console.error('[Admin] Custom claims sync failed for resident:', syncErr.message);
      }
    }

    // Send welcome/creation email using sendWelcomeEmail service
    if (sendEmail && registerInFirebase) {
      try {
        await sendWelcomeEmail({
          email: resident.email.toLowerCase(),
          name: resident.name,
          role: 'resident',
          temporaryPassword: tempPassword,
          isAutoGenerated: true,
        });
      } catch (emailErr: any) {
        console.error('[Admin] Welcome email trigger failed during resident approval:', emailErr.message);
      }
    }

    await logAdminAction({
      adminId: req.user!.id,
      action: 'ADMIN_APPROVE_RESIDENT',
      targetTable: 'residents',
      targetId: residentId,
      details: {
        approvedEmail: resident.email,
      }
    });

    return response.success(res, { residentId }, 'Resident approved and synchronized successfully.');
  } catch (err: any) {
    await client.query('ROLLBACK');
    console.error('[Admin] approveResident error:', err.message);
    return response.error(res, err.message || 'System fault: Failed to approve resident.');
  } finally {
    client.release();
  }
};

