import nodemailer from 'nodemailer';

/**
 * Interface representing the email parameters for a welcome notification.
 */
interface WelcomeEmailParams {
  email: string;
  name: string;
  role: string;
  temporaryPassword?: string;
  isAutoGenerated: boolean;
}

/**
 * Creates an SMTP transporter lazy-loaded using environment variables.
 * Keeps keys hidden and prevents crash-on-startup if credentials are unset.
 */
function getTransporter() {
  const host = process.env.SMTP_HOST;
  const port = process.env.SMTP_PORT ? Number(process.env.SMTP_PORT) : 587;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    return null;
  }

  return nodemailer.createTransport({
    host,
    port,
    secure: port === 465, // True for port 465, false for 587 or other ports
    auth: {
      user,
      pass,
    },
    tls: {
      rejectUnauthorized: false, // Resilience for local self-signed setups
    },
  });
}

/**
 * Sends a welcome email with account information and credentials.
 * If SMTP is not configured, logs details transparently to the console.
 */
export async function sendWelcomeEmail({
  email,
  name,
  role,
  temporaryPassword,
  isAutoGenerated,
}: WelcomeEmailParams): Promise<boolean> {
  const roleLabel =
    role === 'tanod'
      ? 'Barangay Tanod Patrol Officer 👮'
      : role === 'admin'
      ? 'Barangay Central Admin 🛡️'
      : 'Citizen Resident 👤';

  const subject = `[Brgy. Tanod S.O.S] Welcome to the System - ${roleLabel}`;
  const senderAddress = process.env.SMTP_FROM || 'no-reply@brgytanodsos.gov.ph';

  // Aesthetic tactical HTML Mailer Layout
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Brgy. Tanod S.O.S Welcome Account</title>
      <style>
        body {
          font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
          background-color: #0d0f13;
          color: #e2e8f0;
          margin: 0;
          padding: 0;
        }
        .container {
          max-width: 600px;
          margin: 30px auto;
          background-color: #14171e;
          border: 1px solid #1f2937;
          border-radius: 16px;
          overflow: hidden;
          box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.5);
        }
        .header {
          background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%);
          padding: 30px;
          text-align: center;
          border-bottom: 2px solid #00f0ff;
        }
        .header h1 {
          color: #00f0ff;
          font-size: 24px;
          margin: 0;
          text-transform: uppercase;
          letter-spacing: 2px;
          font-weight: 900;
        }
        .header p {
          color: #94a3b8;
          font-size: 11px;
          margin: 8px 0 0 0;
          text-transform: uppercase;
          letter-spacing: 1.5px;
        }
        .content {
          padding: 30px;
          line-height: 1.6;
        }
        .greeting {
          font-size: 18px;
          color: #ffffff;
          font-weight: bold;
          margin-bottom: 20px;
        }
        .credentials-box {
          background-color: #0d0f13;
          border: 1px dashed #00f0ff;
          border-radius: 12px;
          padding: 20px;
          margin: 25px 0;
        }
        .credentials-title {
          font-size: 11px;
          color: #00f0ff;
          text-transform: uppercase;
          letter-spacing: 1px;
          margin-bottom: 10px;
          font-weight: bold;
        }
        .credential-row {
          margin: 8px 0;
          font-family: Courier, monospace;
          font-size: 14px;
        }
        .credential-label {
          color: #64748b;
          display: inline-block;
          width: 140px;
        }
        .credential-value {
          color: #ffffff;
          font-weight: bold;
        }
        .passcode-pill {
          background-color: rgba(0, 240, 255, 0.1);
          color: #00f0ff;
          padding: 3px 8px;
          border-radius: 6px;
          border: 1px solid rgba(0, 240, 255, 0.2);
        }
        .warning-notice {
          border-left: 4px solid #ef4444;
          background-color: rgba(239, 68, 68, 0.05);
          padding: 12px;
          margin: 20px 0;
          font-size: 13px;
          color: #fca5a5;
        }
        .tagalog-localized {
          font-style: italic;
          color: #94a3b8;
          font-size: 13px;
          margin-top: 10px;
          border-top: 1px solid #1f2937;
          padding-top: 10px;
        }
        .footer {
          background-color: #0d0f13;
          padding: 20px;
          text-align: center;
          font-size: 11px;
          color: #475569;
          border-top: 1px solid #1f2937;
        }
        .footer a {
          color: #00f0ff;
          text-decoration: none;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>BRGY. TANOD S.O.S</h1>
          <p>PROACTIVE COMMUNICATIONS ENGINE & HYBRID DEPLOYMENT</p>
        </div>
        <div class="content">
          <div class="greeting">Isang Ligtas na Araw, ${name}!</div>
          <p>Your access profile as a verified <strong>${roleLabel}</strong> has been committed to the Brgy. Tanod S.O.S system network registry.</p>
          
          <div class="credentials-box">
            <div class="credentials-title">System Authorization Manifest</div>
            <div class="credential-row">
              <span class="credential-label">Identity:</span>
              <span class="credential-value">${name}</span>
            </div>
            <div class="credential-row">
              <span class="credential-label">Access Email:</span>
              <span class="credential-value" style="color: #00f0ff;">${email}</span>
            </div>
            <div class="credential-row">
              <span class="credential-label">Security Role:</span>
              <span class="credential-value">${role.toUpperCase()}</span>
            </div>
            ${
              temporaryPassword
                ? `
            <div class="credential-row">
              <span class="credential-label">Access Passcode:</span>
              <span class="credential-value"><code class="passcode-pill">${temporaryPassword}</code></span>
            </div>
            `
                : ''
            }
          </div>

          ${
            isAutoGenerated
              ? `
          <div class="warning-notice">
            <strong>⚠️ IMPORTANT / MAHALAGA:</strong> This is a temporary credential code automatically provisioned by the Barangay Security Administrator. You MUST reset or change your access passcode upon your first system ingress for high-altitude integrity protection!
            <div class="tagalog-localized">
              Mangyaring palitan agad ang inyong password pagka-log-in para sa inyong seguridad at katatagan ng ating barangay S.O.S panel.
            </div>
          </div>
          `
              : `
          <div class="warning-notice" style="border-left-color: #10b981; background-color: rgba(16, 185, 129, 0.05); color: #a7f3d0;">
            <strong>ℹ️ NOTICE:</strong> Your password was manually configured. Please store it in a secure enclave (or keychain) to prevent system lockout during local power or signal outages.
          </div>
          `
          }

          <p style="font-size: 14px; margin-top: 25px;">
            To log in to the responsive dashboard panel, open the application URL from any mobile, tablet, or web device.
          </p>
        </div>
        <div class="footer">
          <p>Brgy. Tanod S.O.S • Emergency Response Command Center</p>
          <p>Philippine Barangay Security & Crisis Operations</p>
          <p style="margin-top: 10px; font-size: 9px; color: #334155;">
            CONFIDENTIAL / INTERNAL SECURITY COMMS. IF RECIPIENT IS INVALID, REPORT TO DISPATCH IMMEDIATE.
          </p>
        </div>
      </div>
    </body>
    </html>
  `;

  const transporter = getTransporter();

  if (!transporter) {
    // Elegant system visual logging of virtual emails when local development or unconfigured offline state
    console.log('\n┌────────────────────────────────────────────────────────────┐');
    console.log('│   📧 [Brgy. Tanod S.O.S] VIRTUAL EMAIL DISPATCH (NO SMTP)   │');
    console.log('├────────────────────────────────────────────────────────────┤');
    console.log(`│   To:        ${email.padEnd(46)} │`);
    console.log(`│   Name:      ${name.padEnd(46)} │`);
    console.log(`│   Subject:   ${subject.slice(0, 42).padEnd(46)} │`);
    console.log(`│   Role:      ${roleLabel.slice(0, 42).padEnd(46)} │`);
    if (temporaryPassword) {
      console.log(`│   Passcode:  ${temporaryPassword.padEnd(46)} │`);
    } else {
      console.log(`│   Passcode:  [MANUALLY SPECIFIED BY ADMIN / HIDDEN]        │`);
    }
    console.log('├────────────────────────────────────────────────────────────┤');
    console.log('│   *SMTP is not configured in environment variables.        │');
    console.log('│   *Please set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS    │');
    console.log('│    in your app environment to dispatch hot SMTP emails.    │');
    console.log('└────────────────────────────────────────────────────────────┘\n');
    return true;
  }

  try {
    const info = await transporter.sendMail({
      from: senderAddress,
      to: email,
      subject,
      html: htmlContent,
    });
    console.log(`[Email] Welcome email dispatched successfully: ${info.messageId}`);
    return true;
  } catch (error: any) {
    console.error('[Email] Failed to dispatch real SMTP email:', error.message);
    // Suppress throwing error to ensure user-creation pipeline doesn't roll back completely
    return false;
  }
}
